{% set name = "segment-lidar" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segment-lidar-{{ version }}.tar.gz
  sha256: 181a35daa802fe2976a53932ad9122b766c2ea91f1bd771d93e3b03b7b6d7b42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9

test:
  imports:
    - segment_lidar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Yarroudh/segment-lidar
  summary: A package for segmenting LiDAR data using Segment-Anything Model (SAM) from Meta AI Research.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://yarroudh.gitbook.io/segment-lidar

extra:
  recipe-maintainers:
    - Yarroudh
    - akharroubi
